/**
 * scripts/import-postgres.ts
 *
 * Reads the backup.json file (generated by export-sqlite.ts) and imports
 * all records into the Supabase PostgreSQL database via Prisma.
 *
 * Usage:
 *   1. Make sure your .env has the Supabase PostgreSQL DATABASE_URL:
 *      DATABASE_URL="postgresql://postgres.xxxx:password@aws-0-xx.pooler.supabase.com:6543/postgres"
 *
 *   2. Run `npx prisma db push` first to ensure schema is deployed:
 *      npx prisma db push
 *
 *   3. Run this script:
 *      npx tsx scripts/import-postgres.ts
 */

import { PrismaClient } from '@prisma/client';
import * as fs from 'fs';
import * as path from 'path';
import * as dotenv from 'dotenv';

dotenv.config();

const prisma = new PrismaClient();

async function main() {
  const backupPath = path.join(process.cwd(), 'backup.json');

  if (!fs.existsSync(backupPath)) {
    console.error('❌ backup.json not found. Run export-sqlite.ts first.');
    process.exit(1);
  }

  const backup = JSON.parse(fs.readFileSync(backupPath, 'utf-8'));
  console.log('📦 Importing data from backup.json into Supabase PostgreSQL...\n');

  // --- Members ---
  if (backup.members?.length > 0) {
    console.log(`  → Importing ${backup.members.length} Members...`);
    for (const row of backup.members) {
      await prisma.member.upsert({
        where: { id: row.id },
        update: {},
        create: {
          id: row.id,
          name: row.name,
          type: row.type,
          imageUrl: row.imageUrl,
          statementEn: row.statementEn,
          statementFr: row.statementFr,
          socialLinks: row.socialLinks,
          createdAt: new Date(row.createdAt),
          updatedAt: new Date(row.updatedAt),
        },
      });
    }
    console.log('     ✅ Members imported');
  }

  // --- Showcases ---
  if (backup.showcases?.length > 0) {
    console.log(`  → Importing ${backup.showcases.length} Showcases...`);
    for (const row of backup.showcases) {
      await prisma.showcase.upsert({
        where: { id: row.id },
        update: {},
        create: {
          id: row.id,
          titleEn: row.titleEn,
          titleFr: row.titleFr,
          artistName: row.artistName,
          mediumEn: row.mediumEn,
          mediumFr: row.mediumFr,
          seriesEn: row.seriesEn ?? '',
          seriesFr: row.seriesFr ?? '',
          statementEn: row.statementEn,
          statementFr: row.statementFr,
          monthYear: row.monthYear,
          galleryItems: row.galleryItems,
          imageUrl: row.imageUrl ?? null,
          createdAt: new Date(row.createdAt),
          updatedAt: new Date(row.updatedAt),
        },
      });
    }
    console.log('     ✅ Showcases imported');
  }

  // --- Podcasts ---
  if (backup.podcasts?.length > 0) {
    console.log(`  → Importing ${backup.podcasts.length} Podcasts...`);
    for (const row of backup.podcasts) {
      await prisma.podcast.upsert({
        where: { id: row.id },
        update: {},
        create: {
          id: row.id,
          titleEn: row.titleEn,
          titleFr: row.titleFr,
          artist: row.artist,
          descriptionEn: row.descriptionEn,
          descriptionFr: row.descriptionFr,
          youtubeId: row.youtubeId,
          imageUrl: row.imageUrl ?? '/podcast-cover.png',
          listenUrl: row.listenUrl ?? null,
          createdAt: new Date(row.createdAt),
          updatedAt: new Date(row.updatedAt),
        },
      });
    }
    console.log('     ✅ Podcasts imported');
  }

  // --- Events ---
  if (backup.events?.length > 0) {
    console.log(`  → Importing ${backup.events.length} Events...`);
    for (const row of backup.events) {
      await prisma.event.upsert({
        where: { id: row.id },
        update: {},
        create: {
          id: row.id,
          titleEn: row.titleEn,
          titleFr: row.titleFr,
          descriptionEn: row.descriptionEn,
          descriptionFr: row.descriptionFr,
          dateEn: row.dateEn ?? '',
          dateFr: row.dateFr ?? '',
          locationEn: row.locationEn ?? 'La Gloria Mexican Coffee, Toronto',
          locationFr: row.locationFr ?? 'La Gloria Mexican Coffee, Toronto',
          capacityEn: row.capacityEn ?? 'Limited to 8-12 guests',
          capacityFr: row.capacityFr ?? 'Limité à 8-12 invités',
          durationEn: row.durationEn ?? '2.5 - 3 hours',
          durationFr: row.durationFr ?? '2.5 - 3 heures',
          imageUrl: row.imageUrl,
          link: row.link ?? null,
          eventDate: row.eventDate ?? '',
          createdAt: new Date(row.createdAt),
          updatedAt: new Date(row.updatedAt),
        },
      });
    }
    console.log('     ✅ Events imported');
  }

  // --- Leads ---
  if (backup.leads?.length > 0) {
    console.log(`  → Importing ${backup.leads.length} Leads...`);
    for (const row of backup.leads) {
      await prisma.lead.upsert({
        where: { id: row.id },
        update: {},
        create: {
          id: row.id,
          name: row.name,
          email: row.email,
          subject: row.subject,
          message: row.message,
          createdAt: new Date(row.createdAt),
          updatedAt: new Date(row.updatedAt),
        },
      });
    }
    console.log('     ✅ Leads imported');
  }

  // --- SiteSettings ---
  if (backup.siteSettings?.length > 0) {
    console.log(`  → Importing ${backup.siteSettings.length} SiteSettings...`);
    for (const row of backup.siteSettings) {
      await prisma.siteSetting.upsert({
        where: { id: row.id },
        update: {},
        create: {
          id: row.id,
          key: row.key,
          value: row.value,
          updatedAt: new Date(row.updatedAt),
        },
      });
    }
    console.log('     ✅ SiteSettings imported');
  }

  console.log('\n🎉 Data import complete!');
}

main()
  .catch((err) => {
    console.error('❌ Import failed:', err);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
